### ISSUE TITLE
win10 cuda11.0 vs2019 torch1.7 can't setup the soft_nms

### ISSUE THREAD

**Issue by Culturenotes** [MrParosk/soft_nms#1]
E:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:E:\Anaconda3\envs\pytorch\lib\site-packages\torch\lib /LIBPATH:E:\Anaconda3\envs\pytorch\libs /LIBPATH:E:\Anaconda3\envs\pytorch\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib /EXPORT:PyInit_soft_nms D:\Googledownload\soft_nms-master\soft_nms-master\build\temp.win-amd64-3.6\Release\Googledownload\soft_nms-master\soft_nms-master\pt_soft_nms\csrc\op.obj D:\Googledownload\soft_nms-master\soft_nms-master\build\temp.win-amd64-3.6\Release\Googledownload\soft_nms-master\soft_nms-master\pt_soft_nms\csrc\soft_nms.obj /OUT:build\lib.win-amd64-3.6\soft_nms.pyd /IMPLIB:D:\Googledownload\soft_nms-master\soft_nms-master\build\temp.win-amd64-3.6\Release\Googledownload\soft_nms-master\soft_nms-master\pt_soft_nms\csrc\soft_nms.lib
LINK : error LNK2001: 无法解析的外部符号 PyInit_soft_nms
D:\Googledownload\soft_nms-master\soft_nms-master\build\temp.win-amd64-3.6\Release\Googledownload\soft_nms-master\soft_nms-master\pt_soft_nms\csrc\soft_nms.lib : fatal error LNK1120: 1 个无法解析的外部命令
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

**Comment by MrParosk** [comment]
The package is not tested under Windows nor is there any CI runs for it. Therefore the installation process can cause issues. I have a windows machine at home which i'll try to see if I can replicate the issue when I have time. Meanwhile, I would recommend installing it on Linux.

**Comment by MrParosk** [comment]
I have updated the code to be compatible with Windows (also added CI tests).

**Comment by Culturenotes** [comment]
Thank you for your contribution！！！
